更新美颜license的设置方法
ZEGOCLOUD/uikit_docs pull request #47
Opened 2024-07-09 09:35 UTC by yoer

2024-07-09 09:46 UTC, Match-Yang commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
为什么美颜的鉴权要写到使用token鉴权这里？单独开个文档吧

2024-07-09 09:48 UTC, Match-Yang requested changes
为什么美颜的鉴权要写到使用token鉴权这里？单独开个文档吧

2024-07-09 09:54 UTC, yoer commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
因为android的也是这么写的，都属于token，我觉得在一篇文章挺好的，不用找来找去

2024-07-09 09:55 UTC, yoer commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
[Android](https://www.zegocloud.com/docs/uikit/callkit-android/advanced-features/use-tokens-for-authentication)

2024-07-09 10:05 UTC, Match-Yang commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
那是你写的知道在token那里。万一客户不用token又要用美颜呢？

2024-07-09 10:08 UTC, Match-Yang commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
搞个叫Face beautification authentication的文档。android应该改一下。不要学他

2024-07-09 10:14 UTC, Match-Yang commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
直接写在美颜这里不行吗：http://localhost:3000/live-streaming-kit-flutter/enhance-the-livestream/advanced-beauty-effects

2024-07-09 10:45 UTC, yoer commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
token是token呀，这是如何用token初始化美颜；两种组合概念，你看着办吧 😴

2024-07-10 03:32 UTC, Match-Yang commented on docs_callkit_flutter/06-Advanced Features/03-Use Tokens for authentication.mdx
> +### Beauty
这是如何使用在线鉴权吧？美颜文档里面我看也没提token概念。接口跟参数也没有token概念

2024-07-10 08:46 UTC, merged